create table if not exists hilleljdbc.persons(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
uid varchar(50) not null,
name varchar(50) not null,
email varchar(50) not null
);

create table if not exists hilleljdbc.accounts(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
uid varchar(50) not null,
iban varchar(50) not null,
balance  INTEGER not null,
person_id INTEGER not null

);