
CREATE TABLE IF NOT EXISTS transactions (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_account_id BIGINT,
  to_account_id BIGINT,
  from_iban VARCHAR(20),
  to_iban VARCHAR(20),
  amount_value numeric(10, 2),
  amount_currency VARCHAR(10),
  create_at TIMESTAMP
);


